//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	config "k8s.io/apiserver/pkg/authentication/config"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AuthenticationConfiguration)(nil), (*config.AuthenticationConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthenticationConfiguration_To_config_AuthenticationConfiguration(a.(*AuthenticationConfiguration), b.(*config.AuthenticationConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AuthenticationConfiguration)(nil), (*AuthenticationConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AuthenticationConfiguration_To_v1alpha1_AuthenticationConfiguration(a.(*config.AuthenticationConfiguration), b.(*AuthenticationConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClaimMappings)(nil), (*config.ClaimMappings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClaimMappings_To_config_ClaimMappings(a.(*ClaimMappings), b.(*config.ClaimMappings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ClaimMappings)(nil), (*ClaimMappings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ClaimMappings_To_v1alpha1_ClaimMappings(a.(*config.ClaimMappings), b.(*ClaimMappings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClaimValidationRule)(nil), (*config.ClaimValidationRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClaimValidationRule_To_config_ClaimValidationRule(a.(*ClaimValidationRule), b.(*config.ClaimValidationRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ClaimValidationRule)(nil), (*ClaimValidationRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ClaimValidationRule_To_v1alpha1_ClaimValidationRule(a.(*config.ClaimValidationRule), b.(*ClaimValidationRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Issuer)(nil), (*config.Issuer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Issuer_To_config_Issuer(a.(*Issuer), b.(*config.Issuer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Issuer)(nil), (*Issuer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Issuer_To_v1alpha1_Issuer(a.(*config.Issuer), b.(*Issuer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JWTAuthenticator)(nil), (*config.JWTAuthenticator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_JWTAuthenticator_To_config_JWTAuthenticator(a.(*JWTAuthenticator), b.(*config.JWTAuthenticator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.JWTAuthenticator)(nil), (*JWTAuthenticator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_JWTAuthenticator_To_v1alpha1_JWTAuthenticator(a.(*config.JWTAuthenticator), b.(*JWTAuthenticator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PrefixedClaimOrExpression)(nil), (*config.PrefixedClaimOrExpression)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PrefixedClaimOrExpression_To_config_PrefixedClaimOrExpression(a.(*PrefixedClaimOrExpression), b.(*config.PrefixedClaimOrExpression), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.PrefixedClaimOrExpression)(nil), (*PrefixedClaimOrExpression)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_PrefixedClaimOrExpression_To_v1alpha1_PrefixedClaimOrExpression(a.(*config.PrefixedClaimOrExpression), b.(*PrefixedClaimOrExpression), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AuthenticationConfiguration_To_config_AuthenticationConfiguration(in *AuthenticationConfiguration, out *config.AuthenticationConfiguration, s conversion.Scope) error {
	out.JWT = *(*[]config.JWTAuthenticator)(unsafe.Pointer(&in.JWT))
	return nil
}

// Convert_v1alpha1_AuthenticationConfiguration_To_config_AuthenticationConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_AuthenticationConfiguration_To_config_AuthenticationConfiguration(in *AuthenticationConfiguration, out *config.AuthenticationConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthenticationConfiguration_To_config_AuthenticationConfiguration(in, out, s)
}

func autoConvert_config_AuthenticationConfiguration_To_v1alpha1_AuthenticationConfiguration(in *config.AuthenticationConfiguration, out *AuthenticationConfiguration, s conversion.Scope) error {
	out.JWT = *(*[]JWTAuthenticator)(unsafe.Pointer(&in.JWT))
	return nil
}

// Convert_config_AuthenticationConfiguration_To_v1alpha1_AuthenticationConfiguration is an autogenerated conversion function.
func Convert_config_AuthenticationConfiguration_To_v1alpha1_AuthenticationConfiguration(in *config.AuthenticationConfiguration, out *AuthenticationConfiguration, s conversion.Scope) error {
	return autoConvert_config_AuthenticationConfiguration_To_v1alpha1_AuthenticationConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ClaimMappings_To_config_ClaimMappings(in *ClaimMappings, out *config.ClaimMappings, s conversion.Scope) error {
	if err := Convert_v1alpha1_PrefixedClaimOrExpression_To_config_PrefixedClaimOrExpression(&in.Username, &out.Username, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PrefixedClaimOrExpression_To_config_PrefixedClaimOrExpression(&in.Groups, &out.Groups, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClaimMappings_To_config_ClaimMappings is an autogenerated conversion function.
func Convert_v1alpha1_ClaimMappings_To_config_ClaimMappings(in *ClaimMappings, out *config.ClaimMappings, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClaimMappings_To_config_ClaimMappings(in, out, s)
}

func autoConvert_config_ClaimMappings_To_v1alpha1_ClaimMappings(in *config.ClaimMappings, out *ClaimMappings, s conversion.Scope) error {
	if err := Convert_config_PrefixedClaimOrExpression_To_v1alpha1_PrefixedClaimOrExpression(&in.Username, &out.Username, s); err != nil {
		return err
	}
	if err := Convert_config_PrefixedClaimOrExpression_To_v1alpha1_PrefixedClaimOrExpression(&in.Groups, &out.Groups, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ClaimMappings_To_v1alpha1_ClaimMappings is an autogenerated conversion function.
func Convert_config_ClaimMappings_To_v1alpha1_ClaimMappings(in *config.ClaimMappings, out *ClaimMappings, s conversion.Scope) error {
	return autoConvert_config_ClaimMappings_To_v1alpha1_ClaimMappings(in, out, s)
}

func autoConvert_v1alpha1_ClaimValidationRule_To_config_ClaimValidationRule(in *ClaimValidationRule, out *config.ClaimValidationRule, s conversion.Scope) error {
	out.Claim = in.Claim
	out.RequiredValue = in.RequiredValue
	return nil
}

// Convert_v1alpha1_ClaimValidationRule_To_config_ClaimValidationRule is an autogenerated conversion function.
func Convert_v1alpha1_ClaimValidationRule_To_config_ClaimValidationRule(in *ClaimValidationRule, out *config.ClaimValidationRule, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClaimValidationRule_To_config_ClaimValidationRule(in, out, s)
}

func autoConvert_config_ClaimValidationRule_To_v1alpha1_ClaimValidationRule(in *config.ClaimValidationRule, out *ClaimValidationRule, s conversion.Scope) error {
	out.Claim = in.Claim
	out.RequiredValue = in.RequiredValue
	return nil
}

// Convert_config_ClaimValidationRule_To_v1alpha1_ClaimValidationRule is an autogenerated conversion function.
func Convert_config_ClaimValidationRule_To_v1alpha1_ClaimValidationRule(in *config.ClaimValidationRule, out *ClaimValidationRule, s conversion.Scope) error {
	return autoConvert_config_ClaimValidationRule_To_v1alpha1_ClaimValidationRule(in, out, s)
}

func autoConvert_v1alpha1_Issuer_To_config_Issuer(in *Issuer, out *config.Issuer, s conversion.Scope) error {
	out.URL = in.URL
	out.CertificateAuthority = *(*[]byte)(unsafe.Pointer(&in.CertificateAuthority))
	out.ClientIDs = *(*[]string)(unsafe.Pointer(&in.ClientIDs))
	return nil
}

// Convert_v1alpha1_Issuer_To_config_Issuer is an autogenerated conversion function.
func Convert_v1alpha1_Issuer_To_config_Issuer(in *Issuer, out *config.Issuer, s conversion.Scope) error {
	return autoConvert_v1alpha1_Issuer_To_config_Issuer(in, out, s)
}

func autoConvert_config_Issuer_To_v1alpha1_Issuer(in *config.Issuer, out *Issuer, s conversion.Scope) error {
	out.URL = in.URL
	out.CertificateAuthority = *(*[]byte)(unsafe.Pointer(&in.CertificateAuthority))
	out.ClientIDs = *(*[]string)(unsafe.Pointer(&in.ClientIDs))
	return nil
}

// Convert_config_Issuer_To_v1alpha1_Issuer is an autogenerated conversion function.
func Convert_config_Issuer_To_v1alpha1_Issuer(in *config.Issuer, out *Issuer, s conversion.Scope) error {
	return autoConvert_config_Issuer_To_v1alpha1_Issuer(in, out, s)
}

func autoConvert_v1alpha1_JWTAuthenticator_To_config_JWTAuthenticator(in *JWTAuthenticator, out *config.JWTAuthenticator, s conversion.Scope) error {
	if err := Convert_v1alpha1_Issuer_To_config_Issuer(&in.Issuer, &out.Issuer, s); err != nil {
		return err
	}
	out.ClaimValidationRules = *(*[]config.ClaimValidationRule)(unsafe.Pointer(&in.ClaimValidationRules))
	if err := Convert_v1alpha1_ClaimMappings_To_config_ClaimMappings(&in.ClaimMappings, &out.ClaimMappings, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_JWTAuthenticator_To_config_JWTAuthenticator is an autogenerated conversion function.
func Convert_v1alpha1_JWTAuthenticator_To_config_JWTAuthenticator(in *JWTAuthenticator, out *config.JWTAuthenticator, s conversion.Scope) error {
	return autoConvert_v1alpha1_JWTAuthenticator_To_config_JWTAuthenticator(in, out, s)
}

func autoConvert_config_JWTAuthenticator_To_v1alpha1_JWTAuthenticator(in *config.JWTAuthenticator, out *JWTAuthenticator, s conversion.Scope) error {
	if err := Convert_config_Issuer_To_v1alpha1_Issuer(&in.Issuer, &out.Issuer, s); err != nil {
		return err
	}
	out.ClaimValidationRules = *(*[]ClaimValidationRule)(unsafe.Pointer(&in.ClaimValidationRules))
	if err := Convert_config_ClaimMappings_To_v1alpha1_ClaimMappings(&in.ClaimMappings, &out.ClaimMappings, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_JWTAuthenticator_To_v1alpha1_JWTAuthenticator is an autogenerated conversion function.
func Convert_config_JWTAuthenticator_To_v1alpha1_JWTAuthenticator(in *config.JWTAuthenticator, out *JWTAuthenticator, s conversion.Scope) error {
	return autoConvert_config_JWTAuthenticator_To_v1alpha1_JWTAuthenticator(in, out, s)
}

func autoConvert_v1alpha1_PrefixedClaimOrExpression_To_config_PrefixedClaimOrExpression(in *PrefixedClaimOrExpression, out *config.PrefixedClaimOrExpression, s conversion.Scope) error {
	out.Claim = in.Claim
	out.Prefix = in.Prefix
	return nil
}

// Convert_v1alpha1_PrefixedClaimOrExpression_To_config_PrefixedClaimOrExpression is an autogenerated conversion function.
func Convert_v1alpha1_PrefixedClaimOrExpression_To_config_PrefixedClaimOrExpression(in *PrefixedClaimOrExpression, out *config.PrefixedClaimOrExpression, s conversion.Scope) error {
	return autoConvert_v1alpha1_PrefixedClaimOrExpression_To_config_PrefixedClaimOrExpression(in, out, s)
}

func autoConvert_config_PrefixedClaimOrExpression_To_v1alpha1_PrefixedClaimOrExpression(in *config.PrefixedClaimOrExpression, out *PrefixedClaimOrExpression, s conversion.Scope) error {
	out.Claim = in.Claim
	out.Prefix = in.Prefix
	return nil
}

// Convert_config_PrefixedClaimOrExpression_To_v1alpha1_PrefixedClaimOrExpression is an autogenerated conversion function.
func Convert_config_PrefixedClaimOrExpression_To_v1alpha1_PrefixedClaimOrExpression(in *config.PrefixedClaimOrExpression, out *PrefixedClaimOrExpression, s conversion.Scope) error {
	return autoConvert_config_PrefixedClaimOrExpression_To_v1alpha1_PrefixedClaimOrExpression(in, out, s)
}
